CERT_PROFILES = {
    "common": {
        "id": "common",
        "name": "AWS General",
        "fullName": "AWS Cloud (General)",
        "domains": [],
        "quickPrompts": [
            {
                "id": "explain",
                "label": "Giải thích",
                "icon": "BookOpen",
                "template": "Giải thích chi tiết về {topic} trong AWS. Bao gồm: định nghĩa, cách hoạt động, use cases chính.",
            },
            {
                "id": "compare",
                "label": "So sánh",
                "icon": "GitCompare",
                "template": "So sánh {topicA} và {topicB} trong AWS. Dùng bảng so sánh với các tiêu chí: mục đích, use case, hiệu suất, chi phí.",
            },
            {
                "id": "when_to_use",
                "label": "Khi nào dùng?",
                "icon": "HelpCircle",
                "template": "Khi nào nên sử dụng {service} trong AWS? Liệt kê các scenarios phù hợp và không phù hợp.",
            },
            {
                "id": "example",
                "label": "Ví dụ thực tế",
                "icon": "Lightbulb",
                "template": "Cho ví dụ thực tế về kiến trúc sử dụng {topic} trên AWS. Vẽ flow bằng text và giải thích từng bước.",
            },
            {
                "id": "practice",
                "label": "Câu hỏi mẫu",
                "icon": "FileQuestion",
                "template": "Tạo 3 câu hỏi trắc nghiệm mẫu về {topic} trong AWS. Mỗi câu có 4 đáp án (A-D) và giải thích chi tiết.",
            },
        ],
        "suggestedQuizTopics": [
            "AWS EC2 Instance Types",
            "Amazon S3 Storage Classes",
            "AWS IAM Policies",
            "Amazon VPC Networking",
            "AWS Lambda",
            "Amazon RDS vs DynamoDB",
            "AWS CloudFormation",
            "Amazon CloudWatch",
        ],
        "systemPromptContext": "General AWS — no specific cert focus.",
    },
    "dea-c01": {
        "id": "dea-c01",
        "name": "AWS DEA-C01",
        "fullName": "AWS Data Engineer Associate",
        "domains": [
            {
                "id": "ingestion",
                "name": "Data Ingestion and Transformation",
                "weight": 34,
                "topics": [
                    "AWS Glue", "AWS Glue DataBrew", "Amazon Kinesis Data Streams",
                    "Amazon Kinesis Data Firehose", "Amazon MSK", "AWS Lambda",
                    "Amazon EMR", "AWS Step Functions", "Amazon AppFlow",
                    "AWS DMS", "AWS DataSync", "Apache Spark on EMR",
                ],
            },
            {
                "id": "store",
                "name": "Data Store Management",
                "weight": 26,
                "topics": [
                    "Amazon S3", "S3 Storage Classes", "Amazon RDS",
                    "Amazon Aurora", "Amazon DynamoDB", "Amazon Redshift",
                    "Amazon ElastiCache", "Amazon OpenSearch Service",
                    "AWS Lake Formation", "Amazon Keyspaces",
                    "Data Lake architecture", "Data Warehouse vs Data Lake",
                ],
            },
            {
                "id": "operations",
                "name": "Data Operations and Support",
                "weight": 22,
                "topics": [
                    "Amazon CloudWatch", "AWS CloudTrail", "Amazon EventBridge",
                    "AWS Systems Manager", "Amazon MWAA (Airflow)",
                    "AWS Glue Workflows", "Amazon SNS", "Amazon SQS",
                    "CI/CD for data pipelines", "Monitoring and alerting",
                ],
            },
            {
                "id": "security",
                "name": "Data Security and Governance",
                "weight": 18,
                "topics": [
                    "AWS IAM", "AWS KMS", "AWS Lake Formation permissions",
                    "Amazon Macie", "AWS Glue Data Catalog",
                    "VPC endpoints", "Encryption at rest and in transit",
                    "Data masking", "Cross-account access", "Resource policies",
                ],
            },
        ],
        "quickPrompts": [
            {
                "id": "explain",
                "label": "Giải thích",
                "icon": "BookOpen",
                "template": "Giải thích chi tiết về {topic} trong AWS Data Engineering. Bao gồm: định nghĩa, cách hoạt động, use cases chính, và exam tips cho DEA-C01.",
            },
            {
                "id": "compare",
                "label": "So sánh",
                "icon": "GitCompare",
                "template": "So sánh {topicA} và {topicB} trong AWS. Dùng bảng so sánh với các tiêu chí: mục đích, use case, hiệu suất, chi phí, và khi nào dùng cái nào trong đề thi DEA-C01.",
            },
            {
                "id": "when_to_use",
                "label": "Khi nào dùng?",
                "icon": "HelpCircle",
                "template": "Khi nào nên sử dụng {service} trong AWS? Liệt kê các scenarios phù hợp và không phù hợp. Đặc biệt lưu ý các tình huống hay gặp trong đề thi DEA-C01.",
            },
            {
                "id": "example",
                "label": "Ví dụ thực tế",
                "icon": "Lightbulb",
                "template": "Cho ví dụ thực tế về kiến trúc data pipeline sử dụng {topic} trên AWS. Vẽ flow bằng text và giải thích từng bước.",
            },
            {
                "id": "practice",
                "label": "Câu hỏi mẫu",
                "icon": "FileQuestion",
                "template": "Tạo 3 câu hỏi trắc nghiệm mẫu về {topic} theo format đề thi AWS DEA-C01. Mỗi câu có 4 đáp án (A-D) và giải thích chi tiết đáp án đúng/sai.",
            },
        ],
        "suggestedQuizTopics": [
            "AWS Glue ETL",
            "Amazon Kinesis vs MSK",
            "Amazon S3 Storage Classes",
            "Amazon Redshift",
            "AWS Lake Formation",
            "Data Pipeline Orchestration",
            "AWS KMS Encryption",
            "Amazon DynamoDB",
        ],
        "systemPromptContext": "Cert: DEA-C01. Domains: Ingestion 34%, Store 26%, Operations 22%, Security 18%.",
    },
    "saa-c03": {
        "id": "saa-c03",
        "name": "AWS SAA-C03",
        "fullName": "AWS Solutions Architect Associate",
        "domains": [
            {
                "id": "secure",
                "name": "Design Secure Architectures",
                "weight": 30,
                "topics": [
                    "AWS IAM", "AWS Organizations", "AWS STS",
                    "Amazon Cognito", "AWS Directory Service",
                    "Security Groups vs NACLs", "AWS WAF & Shield",
                    "AWS KMS", "AWS Certificate Manager",
                    "VPC design", "Private/Public subnets",
                ],
            },
            {
                "id": "resilient",
                "name": "Design Resilient Architectures",
                "weight": 26,
                "topics": [
                    "Multi-AZ deployments", "Auto Scaling",
                    "Elastic Load Balancing (ALB/NLB/GWLB)",
                    "Amazon SQS decoupling", "Amazon Route 53 routing policies",
                    "Disaster recovery strategies", "RDS Multi-AZ vs Read Replicas",
                    "S3 replication", "AWS Backup",
                    "Loosely coupled architectures",
                ],
            },
            {
                "id": "performing",
                "name": "Design High-Performing Architectures",
                "weight": 24,
                "topics": [
                    "Amazon EC2 instance types", "EBS volume types",
                    "Amazon EFS vs FSx", "Amazon ElastiCache",
                    "Amazon CloudFront", "AWS Global Accelerator",
                    "Amazon Aurora", "Amazon DynamoDB",
                    "AWS Lambda", "Amazon API Gateway",
                ],
            },
            {
                "id": "cost",
                "name": "Design Cost-Optimized Architectures",
                "weight": 20,
                "topics": [
                    "EC2 pricing models (On-Demand, Reserved, Spot, Savings Plans)",
                    "S3 storage classes & lifecycle policies",
                    "AWS Cost Explorer", "AWS Budgets",
                    "Right-sizing", "AWS Trusted Advisor",
                    "Data transfer costs", "Serverless cost optimization",
                ],
            },
        ],
        "quickPrompts": [
            {
                "id": "explain",
                "label": "Giải thích",
                "icon": "BookOpen",
                "template": "Giải thích chi tiết về {topic} trong AWS Solutions Architecture. Bao gồm: định nghĩa, cách hoạt động, use cases chính, và exam tips cho SAA-C03.",
            },
            {
                "id": "compare",
                "label": "So sánh",
                "icon": "GitCompare",
                "template": "So sánh {topicA} và {topicB} trong AWS. Dùng bảng so sánh với các tiêu chí: mục đích, use case, hiệu suất, chi phí, và khi nào dùng cái nào trong đề thi SAA-C03.",
            },
            {
                "id": "when_to_use",
                "label": "Khi nào dùng?",
                "icon": "HelpCircle",
                "template": "Khi nào nên sử dụng {service} trong AWS? Liệt kê các scenarios phù hợp và không phù hợp. Đặc biệt lưu ý các tình huống hay gặp trong đề thi SAA-C03.",
            },
            {
                "id": "architecture",
                "label": "Thiết kế kiến trúc",
                "icon": "Lightbulb",
                "template": "Thiết kế kiến trúc AWS cho bài toán: {topic}. Vẽ architecture diagram bằng text, giải thích từng component và lý do chọn.",
            },
            {
                "id": "practice",
                "label": "Câu hỏi mẫu",
                "icon": "FileQuestion",
                "template": "Tạo 3 câu hỏi trắc nghiệm mẫu về {topic} theo format đề thi AWS SAA-C03. Mỗi câu có 4 đáp án (A-D) và giải thích chi tiết đáp án đúng/sai.",
            },
        ],
        "suggestedQuizTopics": [
            "EC2 Instance Types & Pricing",
            "S3 Storage Classes",
            "VPC & Networking",
            "ALB vs NLB vs GWLB",
            "Auto Scaling Strategies",
            "RDS Multi-AZ vs Read Replicas",
            "Disaster Recovery on AWS",
            "Serverless Architecture",
        ],
        "systemPromptContext": "Cert: SAA-C03. Domains: Secure 30%, Resilient 26%, High-Performing 24%, Cost-Optimized 20%.",
    },
    "sap-c02": {
        "id": "sap-c02",
        "name": "AWS SAP-C02",
        "fullName": "AWS Solutions Architect Professional",
        "domains": [
            {
                "id": "complexity",
                "name": "Design for Organizational Complexity",
                "weight": 26,
                "topics": [
                    "AWS Organizations", "Service Control Policies (SCPs)",
                    "Multi-account strategies", "AWS Control Tower",
                    "Cross-account access", "AWS RAM",
                    "Hybrid connectivity (Direct Connect, VPN)",
                    "Transit Gateway", "Network design patterns",
                ],
            },
            {
                "id": "new_solutions",
                "name": "Design for New Solutions",
                "weight": 29,
                "topics": [
                    "Microservices architecture", "Event-driven architecture",
                    "Serverless patterns", "Container orchestration (ECS/EKS)",
                    "Data lakes & analytics", "Machine learning pipelines",
                    "IoT architectures", "Real-time processing",
                    "API design patterns", "Decoupling strategies",
                ],
            },
            {
                "id": "migration",
                "name": "Migration Planning",
                "weight": 25,
                "topics": [
                    "AWS Migration Hub", "AWS Application Discovery Service",
                    "6R migration strategies", "AWS DMS",
                    "AWS Snow Family", "VMware Cloud on AWS",
                    "Database migration strategies",
                    "Large-scale data transfer", "Application modernization",
                ],
            },
            {
                "id": "cost_perf",
                "name": "Cost Control & Performance Optimization",
                "weight": 20,
                "topics": [
                    "AWS Cost Explorer & Budgets", "Reserved Instances & Savings Plans",
                    "Performance monitoring & optimization",
                    "Caching strategies", "CDN optimization",
                    "Database performance tuning",
                    "Compute right-sizing", "Storage tiering",
                ],
            },
        ],
        "quickPrompts": [
            {
                "id": "explain",
                "label": "Giải thích",
                "icon": "BookOpen",
                "template": "Giải thích chi tiết về {topic} ở mức professional-level AWS. Bao gồm: deep-dive, trade-offs, và exam tips cho SAP-C02.",
            },
            {
                "id": "compare",
                "label": "So sánh",
                "icon": "GitCompare",
                "template": "So sánh {topicA} và {topicB} trong AWS ở mức professional. Phân tích trade-offs, edge cases, và khi nào chọn cái nào trong đề thi SAP-C02.",
            },
            {
                "id": "scenario",
                "label": "Scenario Analysis",
                "icon": "HelpCircle",
                "template": "Phân tích scenario sau ở mức professional: {topic}. Đưa ra kiến trúc tối ưu, giải thích trade-offs, và lưu ý cho đề thi SAP-C02.",
            },
            {
                "id": "architecture",
                "label": "Thiết kế kiến trúc",
                "icon": "Lightbulb",
                "template": "Thiết kế kiến trúc enterprise-grade AWS cho: {topic}. Bao gồm multi-account strategy, security, HA, DR, và cost optimization.",
            },
            {
                "id": "practice",
                "label": "Câu hỏi mẫu",
                "icon": "FileQuestion",
                "template": "Tạo 3 câu hỏi trắc nghiệm mẫu professional-level về {topic} theo format đề thi AWS SAP-C02. Scenario dài, 4-5 đáp án, giải thích chi tiết.",
            },
        ],
        "suggestedQuizTopics": [
            "Multi-Account Strategy",
            "Hybrid Cloud Architecture",
            "6R Migration Strategies",
            "Event-Driven Architecture",
            "Container Orchestration (ECS vs EKS)",
            "Cross-Region Disaster Recovery",
            "Cost Optimization at Scale",
            "Network Design (Transit Gateway, Direct Connect)",
        ],
        "systemPromptContext": "Cert: SAP-C02 (Professional). Domains: Complexity 26%, New Solutions 29%, Migration 25%, Cost/Perf 20%.",
    },
    "aif-c01": {
        "id": "aif-c01",
        "name": "AWS AIF-C01",
        "fullName": "AWS Certified AI Practitioner",
        "domains": [
            {
                "id": "foundations",
                "name": "AI and ML Foundations",
                "weight": 24,
                "topics": [
                    "AI vs ML vs Deep Learning",
                    "Supervised vs Unsupervised Learning",
                    "Generative AI fundamentals",
                    "LLM basics (tokens, context window, temperature)",
                    "Model evaluation metrics",
                    "Overfitting vs underfitting",
                ],
            },
            {
                "id": "aws_ai_services",
                "name": "AWS AI Services and Use Cases",
                "weight": 34,
                "topics": [
                    "Amazon Bedrock",
                    "Bedrock Knowledge Bases",
                    "Bedrock Guardrails",
                    "Amazon SageMaker (high-level)",
                    "Amazon Textract",
                    "Amazon Comprehend",
                    "Amazon Rekognition",
                    "Amazon Transcribe",
                    "Amazon Translate",
                    "Amazon Lex",
                    "Amazon Kendra",
                    "Use-case to service mapping",
                ],
            },
            {
                "id": "prompt_and_app_design",
                "name": "Prompt Engineering and AI App Design",
                "weight": 26,
                "topics": [
                    "Prompt patterns and constraints",
                    "Few-shot prompting",
                    "Grounding and RAG basics",
                    "Vector embeddings and vector stores",
                    "Hallucination mitigation",
                    "Latency vs quality trade-offs",
                    "Cost-aware prompt design",
                ],
            },
            {
                "id": "responsible_ai",
                "name": "Responsible AI, Security, and Governance",
                "weight": 16,
                "topics": [
                    "Responsible AI principles",
                    "Bias, fairness, and explainability",
                    "Data privacy and PII handling",
                    "Prompt injection risks",
                    "Model safety controls",
                    "IAM and least privilege for AI workloads",
                    "Compliance basics for AI solutions",
                ],
            },
        ],
        "quickPrompts": [
            {
                "id": "explain",
                "label": "Giải thích",
                "icon": "BookOpen",
                "template": "Giải thích chi tiết về {topic} trong ngữ cảnh AWS AI Practitioner (AIF-C01). Bao gồm: khái niệm cốt lõi, khi nào dùng, khi nào không nên dùng, và exam tips.",
            },
            {
                "id": "compare",
                "label": "So sánh",
                "icon": "GitCompare",
                "template": "So sánh {topicA} và {topicB} trong AWS AI. Dùng bảng theo tiêu chí: mục đích, dữ liệu đầu vào, đầu ra, chi phí, độ chính xác, và bẫy hay gặp trong đề AIF-C01.",
            },
            {
                "id": "when_to_use",
                "label": "Khi nào dùng?",
                "icon": "HelpCircle",
                "template": "Khi nào nên dùng {service} trong AWS AI? Liệt kê các scenario phù hợp/không phù hợp, cùng dấu hiệu nhận biết nhanh khi làm câu hỏi AIF-C01.",
            },
            {
                "id": "architecture",
                "label": "Thiết kế AI flow",
                "icon": "Lightbulb",
                "template": "Thiết kế AI workflow cho bài toán: {topic}. Mô tả flow bằng text, chỉ ra dịch vụ AWS phù hợp (Bedrock/SageMaker/AI services), và cách tối ưu cost-latency.",
            },
            {
                "id": "practice",
                "label": "Câu hỏi mẫu",
                "icon": "FileQuestion",
                "template": "Tạo 3 câu hỏi trắc nghiệm mẫu về {topic} theo format AWS AIF-C01. Mỗi câu có 4 đáp án (A-D), chỉ rõ đáp án đúng và giải thích vì sao các đáp án còn lại sai.",
            },
        ],
        "suggestedQuizTopics": [
            "Amazon Bedrock Fundamentals",
            "Prompt Engineering Basics",
            "RAG and Knowledge Bases",
            "Bedrock Guardrails and Safety",
            "Choosing the Right AWS AI Service",
            "SageMaker vs Bedrock (high level)",
            "Responsible AI and Bias Mitigation",
            "AI Security and Data Privacy",
        ],
        "systemPromptContext": "Cert: AIF-C01 (AWS Certified AI Practitioner). Focus: AI/ML foundations, AWS AI services, prompt engineering + RAG basics, and responsible AI/security.",
    },
}


def get_profile(cert_id: str) -> dict:
    return CERT_PROFILES.get(cert_id, CERT_PROFILES["common"])


def get_all_profiles_summary() -> list[dict]:
    return [
        {"id": p["id"], "name": p["name"], "fullName": p["fullName"]}
        for p in CERT_PROFILES.values()
    ]
